language_model:
  type: transformers
  checkpoint: microsoft/DialoGPT-small
  pretrained: True
  save_location: './models/dialoGPT_dailyDialog_finetuned/'
dataset:
  type: 'daily_dialogue'
  size_train: 1000
  size_test: 25
  batch_size: 32
  subsets: start
  remove_top_n: 10
tokenizer:
  type: transformers
  checkpoint: 'microsoft/DialoGPT-small'
hparams:
  learning_rate: 0.001
  freeze_language_ml: False
  teacher_forcing: True
loss_module: crossentropyloss
trainer:
  type: policy #Type of the pytorch lighntning model we are training.
  max_epochs: 25
  log_every_n_steps: 1
rational_extractor:
  type: shared_embedding
  pretrained: False
  save_location: './models/shared_embed_gpt2.pt'