language_model:
  type: transformers
  checkpoint: microsoft/DialoGPT-small
  pretrained: False
  save_location: './models/dialoGPT_dailyDialog_finetuned/'
dataset:
  type: 'daily_dialogue'
  size_train: 1000
  size_test: 1000
  batch_size: 8
  subsets: start
  remove_top_n: 100
tokenizer:
  type: transformers
  checkpoint: 'microsoft/DialoGPT-small'
hparams:
  learning_rate: 0.001
  freeze_language_model: False
loss_module: crossentropyloss
trainer:
  type: policy #Type of the pytorch lighntning model we are training.
  max_epochs: 50
  log_every_n_steps: 1
rational_extractor:
  type: policy_based