language_model:
  type: transformers
  load_location: './finetuning/saved_models/roberta-daily_dialog'
  checkpoint: distilroberta-base
  pretrained: True
  save_location: './final_models/roberta-daily_dialog.pt'
dataset:
  type: 'daily_dialogue'
  size_train: 10000
  size_test: 10000
  batch_size: 8
  subsets: start
  remove_top_n: 0 #100
tokenizer:
  type: transformers
  checkpoint: 'distilroberta-base'
hparams:
  learning_rate: 0.001
  freeze_language_model: False
loss_module: crossentropyloss
trainer:
  type: policy #Type of the pytorch lighntning model we are training.
  max_epochs: 5
  log_every_n_steps: 1
rational_extractor:
  pretrained: False
  type: policy_based
  save_location: './models/RE_REINFORCE_roberta.pt'
  load_location: './models/RE_REINFORCE_roberta.pt'
  parameters:
    fussed_lasso_weight: 0.01
    sparsity_weight: 0.1