language_model:
  type: LSTM
  pretrained: True
  embedding_dim: 128
  num_layers: 2
  hidden_state_size: 128
  load_location: './models/small_lm_test.pt'
  save_location: './models/freeze_small_lm_test_rationalized.pt'
dataset:
  type: 'daily_dialogue'
  size_train: 1000
  size_test: 25
  batch_size: 32
  subsets: start
  remove_top_n: 10
tokenizer:
  type: 'daily_dialogue'
  link: './daily_dialog/tokenizer.json'
hparams:
  learning_rate: 0.001
  freeze_language_ml: True
  teacher_forcing: True
loss_module: crossentropyloss
trainer:
  type: policy #Type of the pytorch lighntning model we are training.
  max_epochs: 25
  log_every_n_steps: 1
rational_extractor:
  type: shared_embedding
  pretrained: False
  # load_location: './models/shared_simple.pt'
  save_location: './models/shared_simple_freeze.pt'





