language_model:
  type: LSTM
  pretrained: False
  embedding_dim: 128
  num_layers: 2
  hidden_state_size: 128
  save_location: './models/lstm.pt'
  load_location: './models/lstm_finetuned.pt'
dataset:
  type: 'daily_dialogue'
  size_train: 10000
  size_test: 10000
  remove_top_n: 20
  batch_size: 32
  subsets: start
tokenizer:
  type: 'daily_dialogue'
  link: './daily_dialog/tokenizer.json'
hparams:
  learning_rate: 0.001
loss_module: crossentropyloss
trainer:
  type: normal #normal vs rationalized type
  max_epochs: 50
  log_every_n_steps: 1




